# Site settings
title: Hybrid
email: david.godfrey99@gmail.com
description: "An extensive hierarchy of exception classes written in C++11"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dgodfrey95.github.io"
twitter_username: jekyllrb
github_username:  dgodfrey95

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
exclude: ["README", "README.md", "vendor", "node_modules"]

theme: jekyll-theme-minimal